config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  # :controllers => {:registrations => "users/registrations"}
  #scope "(:locale)", locale: /en|vi|ja/ do
  # devise_scope :user do
  #   root to: "devise/sessions#new"
  # end
  root 'static_pages#home'
  mount ActionCable.server => '/cable'

  get 'home' => 'static_pages#home'

  namespace :members do
    root 'static_pages#home'
    resources :users do
      resources :posts do
        resources :comments
      end
    end
    resources :user_courses
    resources :courses do
      resources :lessons do
        resources :exams
      end
    end
    resources :activities, only: :index
    resource :user_settings, only: :show
    resources :register_courses, only: [:index, :show, :create]
    resources :registered_courses, only: :index
    resources :notifies
  end

  namespace :teachers do
    # root 'courses#index'
    resources :users, only: [:show, :edit, :update]
    resources :courses do
      resources :lessons do
        resources :questions
        resources :time_for_exams
      end
      resources :user_courses,  only: [:index, :create]
      resource :user_courses, only: :destroy
      resources :register_courses
    end
    resource :user_settings, only: :show
    resources :user_register_courses, only: :index
    resources :set_status_user_register_courses, only: :index
    resources :activities, only: :index
    resources :notifies
  end

  namespace :admins do
    resources :users
    resources :categories do
      resources :types
    end
    resources :courses
    resources :set_status_courses, only: [:index, :show]
    resource :user_settings, only: :show
    resources :activities, only: :index
    resources :notifies
  end

  namespace :publish do
    resources :posts do
      resources :comments
    end
    resources :rooms
  end

  # namespace :member do
  #   resources :posts do
  #     resources :comments
  #   end
  # end


    # resources :workspaces do
    #   resource :user_workspaces, except: [:show]
    # end
end

app/models/category.rb
class Category < ApplicationRecord
  # acts_as_paranoid

  has_many :types, dependent: :destroy

  accepts_nested_attributes_for :types, allow_destroy: true,
    reject_if: proc { |attributes| attributes[:name].blank? }

  scope :recent, ->{order created_at: :desc}

  validates :name, presence: true, length: {maximum: 255, minimum: 2}
end

app/controllers/admins/categories_controller.rb
class Admins::CategoriesController < DashboardController
  before_action :load_category, except: [:index, :new, :create]
  load_and_authorize_resource
  before_action :authenticate_admin!, only: [:index, :new, :edit, :update, :destroy]

  def index
    @search = Category.ransack(params[:q])
    @categories =  @search.result.recent.page(params[:page])
      .per Settings.per_page.admins.category
    if request.xhr?
      respond_to do |format|
        format.js{}
      end
    end
  end

  def new
    @category = Category.new
    @type = @category.types.build
  end

  def create
    @category = Category.new category_params
    if @category.save
      create_activity_for_category
      flash[:success] = "Tạo danh mục thành công"
      redirect_to admins_categories_path
    else
      render :new
    end
  end

  def show
    @category = Category.find_by id: params[:id]
    if params[:name].eql? Course.name
      render partial: "teachers/courses/type", local: {types: @category.types}
    elsif  params[:name].eql? Post.name
      render partial: "members/posts/type", local: {types: @category.types}
    else
      respond_to do |format|
        format.html{render partial: "details_information", local: {category: @category}}
      end
    end
  end

  def edit; end

  def update
    if @category.update_attributes category_params
      create_activity_for_category
      flash[:success] = "Cập nhật danh mục thành công"
      redirect_to admins_categories_path
    else
      render :edit
    end
  end

  def destroy
    @category.types.each do |type|
      if type.courses.present? || type.posts.present?
        @destroy = true
        break
      end
    end
    if @destroy.blank?
      if @category.destroy
        # create_activity_for_category
        flash[:success] = "Xóa danh mục thành công"
      else
        flash[:error] = "Xóa danh mục không thành công"
      end
    else
      flash[:error] = "Không thể xóa danh mục này"
    end
    redirect_to admins_categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name, :description, types_attributes: [:id, :name, :_destroy])
  end

  def load_category
    @category = Category.find_by id: params[:id]
    return if @category
    flash[:error] = "Không tìm thấy danh mục"
    redirect_to admins_categories_path
  end

  def create_activity_for_category
    create_activity Category.name, @category, @_action_name
  end
end

app/helpers/admins/categories_helper.rb
module Admins::CategoriesHelper
end

app/views/admins/categories/_category.html.erb
<tr>
  <td>
    <%= current_index @categories.current_page, Settings.per_page.admins.category,
      category_counter %>
  </td>
  <td><%= category.name %></td>
  <td><%= category.description %></td>
  <td>
    <div class="btn-group btn-group-xs">
      <%= render "shared/btn_show", object: category %>
      <%= link_to edit_admins_category_path(category), class: "btn btn-warning" do %>
        <i class="fa fa-pencil"></i>
      <% end %>
      <%= link_to admins_category_path(category),
        method: :delete, class: "btn btn-danger", data: {confirm: "Bạn có chắc chắn muốn xóa không?"} do %>
        <i class="fa fa-trash"></i>
      <% end %>
      </div>
  </td>
</tr>

app/views/admins/categories/_details_information.html.erb
<div class="panel panel-info">
  <div class="panel-heading">
    <center><h3 class="panel-title">Chi tiết danh mục</h3></center>
  </div>
  <div class="panel-body">
    <div class="row">
      <table class="table margin-bottom-0">
        <tbody>
          <tr>
            <td>Tên</td>
            <td><%= @category.name %></td>
          </tr>
          <tr>
            <td>Mô tả</td>
            <td><%= @category.description %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admins/categories/_form.html.erb
<div class="panel panel-info">
  <div class="panel-heading">
    <center><h3 class="panel-title"><%= yield(:title) %></h3></center>
  </div>
  <div class="panel-body">
    <div class="container form-horizontal">
      <%= form_for [:admins, @category] do |f| %>
        <div class="form-group">
          <div class="col-md-offset-3">
            <%= render "shared/error_messages", object: f.object %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :name, value: "Tên danh mục", class: "col-md-3 control-label" %>
          <div class="col-md-5">
            <%= f.text_field :name, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :description, value: "Mô tả", class: "col-md-3  control-label" %>
          <div class="col-md-5">
            <%= f.text_field :description, class: "form-control" %>
          </div>
        </div>

        <%= f.fields_for :types do |ff| %>
          <div class="clear-fix types-form">
            <div class="form-group">
              <%= ff.label :name, value: "Loại", class: "col-md-3 control-label" %>
              <div class="col-md-5">
                <%= ff.text_field :name, class: "form-control" %>
              </div>
              <div class="col-md-4 remove-answer">
                <%= link_to_remove_fields_type "Xóa", ff %>
              </div>
            </div>
          </div>
        <% end %>

        <div class="clear-fix form-group add-type row">
          <div class="col-md-offset-2">
            <%= link_to_add_fields "Thêm", f, :types,
              class: "btn btn-sm btn-primary fa fa-plus" %>
          </div>
        </div>

        <div class="form-group" >
          <div class="col-md-5 col-md-offset-3">
            <%= f.submit yield(:button_text),
              class: "btn btn-primary form-control" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admins/categories/_table_category.html.erb
<% if @categories.present? %>
  <table class="table table-bordered table-hover">
    <thead>
      <tr class="table-center">
        <th class="font-size-15"> Stt </th>
        <th class="font-size-15"><%= sort_link @search, :name, "Tên", {},
          {:remote => true} %>
        </th>
        <th class="font-size-15" style="min-width: 250px; max-width: 300px"> Mô tả </th>
        <th class="font-size-15"> Thao tác </th>
      </tr>
    </thead>
    <tbody class="table-center">
      <%= render(@categories, categories: @categories) %>
    </tbody>
  </table>
  <center><%= paginate @categories, remote: true %></center>
<% end %>

app/views/admins/categories/_type_fields.html.erb
<div class="clear-fix types-form" style="padding-left: 11px; padding-right:10px">
  <div class="form-group">
    <%= f.label :name, value: "Loại", class: "col-md-3 control-label" %>
    <div class="col-md-5">
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="col-md-4 remove-answer">
      <%= link_to_remove_fields_type "Xóa", f %>
    </div>
  </div>
</div>

app/views/admins/categories/edit.html.erb
<% provide :title, "Chỉnh sửa danh mục" %>
<% provide :button_text, "Cập nhật" %>
<div class="panel-content">
  <%= render "form" %>
</div>

app/views/admins/categories/index.html.erb
<% provide :title, "Danh sách danh mục" %>
<%= link_to new_admins_category_path,
  class: "btn btn-sm btn-success" do %>
  <i class="gi gi-plus"></i> Thêm danh mục
<% end %>
<br>
<br>
<div class="clear-fix panel panel-default">
  <div class="panel-heading">Tìm kiếm</div>
  <div class="panel-body">
    <%= search_form_for [:admins, @search], class: "row col-md-offset-2", remote: true do |f| %>
      <div class="form-group col-md-8">
        <%= f.text_field :name_or_description_cont,
          placeholder: "Nhập tên danh mục hoặc mô tả",
          class: "form-control" %>
      </div>
      &nbsp;&nbsp;
      <%= link_to admins_categories_path do %>
        <i class="fa fa-refresh btn btn-success"></i>
      <% end %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="row clear-fix col-center color-red" id="not-exist-categories-search">
    </div>
    <div class="table-responsive" id="list-categories-search">
      <%= render "table_category" %>
    </div>
  </div>
</div>
 <div class="modal_show_details"><%= render "shared/model_show" %></div>

app/views/admins/categories/index.js.erb
$('#list-categories-search')
  .html('<%= j render("table_category") %>');
$('#not-exist-categories-search').html('<%= "Dữ liệu không tìm thấy" if @search.result.blank? %>');

app/views/admins/categories/new.html.erb
<% provide :title, "Thêm mới danh mục" %>
<% provide :button_text, "Tạo" %>
<div class="panel-content">
  <%= render "form" %>
</div>