config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  # :controllers => {:registrations => "users/registrations"}
  #scope "(:locale)", locale: /en|vi|ja/ do
  # devise_scope :user do
  #   root to: "devise/sessions#new"
  # end
  root 'static_pages#home'
  mount ActionCable.server => '/cable'

  get 'home' => 'static_pages#home'

  namespace :members do
    root 'static_pages#home'
    resources :users do
      resources :posts do
        resources :comments
      end
    end
    resources :user_courses
    resources :courses do
      resources :lessons do
        resources :exams
      end
    end
    resources :activities, only: :index
    resource :user_settings, only: :show
    resources :register_courses, only: [:index, :show, :create]
    resources :registered_courses, only: :index
    resources :notifies
  end

  namespace :teachers do
    # root 'courses#index'
    resources :users, only: [:show, :edit, :update]
    resources :courses do
      resources :lessons do
        resources :questions
        resources :time_for_exams
      end
      resources :user_courses,  only: [:index, :create]
      resource :user_courses, only: :destroy
      resources :register_courses
    end
    resource :user_settings, only: :show
    resources :user_register_courses, only: :index
    resources :set_status_user_register_courses, only: :index
    resources :activities, only: :index
    resources :notifies
  end

  namespace :admins do
    resources :users
    resources :categories do
      resources :types
    end
    resources :courses
    resources :set_status_courses, only: [:index, :show]
    resource :user_settings, only: :show
    resources :activities, only: :index
    resources :notifies
  end

  namespace :publish do
    resources :posts do
      resources :comments
    end
    resources :rooms
  end

  # namespace :member do
  #   resources :posts do
  #     resources :comments
  #   end
  # end


    # resources :workspaces do
    #   resource :user_workspaces, except: [:show]
    # end
end

app/models/user.rb
class User < ApplicationRecord

  # attr_accessor :validate_other

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ratyrate_rater

  # def initialize *args
  #   self.validate_other ||= true
  #   super(*args)
  # end

  after_create :create_user_setting

  has_many :posts, dependent: :destroy
  has_many :user_courses, dependent: :destroy
  has_many :courses, through: :user_courses
  has_many :exams, dependent: :destroy
  has_many :activities
  has_many :notifications
  has_many :comments

  has_one :user_setting, dependent: :destroy

  scope :recent, ->{order created_at: :desc}
  scope :by_member, ->{where role: :member}
  scope :by_teacher, ->{where role: :teacher}
  scope :by_admin, ->{where role: :admin}
  scope :not_in_course, ->course_id do
    where "id NOT IN (select user_id from user_courses where course_id = ? and status = 1)", course_id
  end

  mount_uploader :avatar, AvatarUploader

  enum gender: {female: 0, male: 1, other: 2}
  enum role: {admin: 0, teacher: 1, member: 2}

  # validates :name, :number_of_phone, presence: true, on: :update
  validate :image_size

  def is_user? user
    id == user.id
  end

  def create_user_setting
    UserSetting.create user_id: self.id
  end

  private

  def image_size
    if avatar.size > Settings.max_size_image_avatar.megabytes
      errors.add :avatar, I18n.t("dashboard.users.message_error_image_avatar")
    end
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < DashboardController
  before_action :load_user, except: [:index, :new, :create]
  before_action :valid_image_avatar, only: [:create, :update]
  load_and_authorize_resource
  before_action :authenticate_admin!

  def index
    @search = User.ransack(params[:q])
    @users = @search.result.recent.page(params[:page])
      .per Settings.per_page.admins.user
    @roles = User.roles
    if request.xhr?
      respond_to do |format|
        format.js{}
      end
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params.merge!(password: "123456")
    if @user.save
      create_activity_for_user
      flash[:success] = "Thêm thành viên thành công"
      redirect_to admins_users_path
    else
      render :new
    end
  end

  def show

  end

  def edit; end

  def update
    if @user.update_attributes user_params
      create_activity_for_user
      flash[:success] = "Cập nhật thành viên thành công"
      redirect_to admins_users_path
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      # create_activity_for_user
      flash[:success] = "Xóa thành viên thành công"
    else
      flash[:warning] = "Xóa thành viên không thành công"
    end
    redirect_to admins_users_path
  end

  private

  def valid_image_avatar
    if params[:user][:avatar].present?
      unless Settings.image_types.to_h.values.include? File.extname(
        params[:user][:avatar].original_filename).split(".").last.downcase
        flash[:error] = "Ảnh không đúng định dạng"
        redirect_to :back
      end
    end
  end


  def user_params
    params.require(:user).permit(:email, :name, :gender, :avatar,
      :birthday, :role, :address, :number_of_phone)
  end

  def load_user
    @user = User.find_by id: params[:id]
    return if @user
    flash[:error] = "Không tìm thấy thành viên"
    redirect_to admins_users_path
  end

  def create_activity_for_user
    create_activity User.name, @user, @_action_name
  end
end

app/controllers/members/users_controller.rb
class Members::UsersController < ApplicationController
  # before_action :authenticate_user!
  before_action :load_user, except: [:index, :new]
  before_action :valid_image_avatar, only: [:create, :update]
  load_and_authorize_resource

  def index
    @users = User.recent.page(params[:page])
      .per Settings.per_page.members.user
  end

  def new
    @user = User.new
  end

  # def create
  #   @user = User.new user_params
  #   if @user.save
  #     create_activity_for_user
  #     flash[:success] = t "devise.registrations.signed_up"
  #     redirect_to members_users_path
  #   else
  #     render :new
  #   end
  # end

  def show
  end

  def edit; end

  def update
    if @user.update_attributes user_params
      create_activity_for_user
      flash[:success] = "Cập nhật thành công"
      redirect_to members_user_posts_path(current_user)
    else
      render :edit
    end
  end

  # def destroy
  #   if @user.destroy
  #     create_activity_for_user
  #     flash[:success] = t "devise.registrations.destroyed"
  #   else
  #     flash[:warning] = t "delete_not_success"
  #   end
  #   redirect_to members_users_path
  # end

  private

  def valid_image_avatar
    if params[:user][:avatar].present?
      unless Settings.image_types.to_h.values.include? File.extname(
        params[:user][:avatar].original_filename).split(".").last.downcase
        flash[:error] = "Ảnh quá lớn"
        redirect_to :back
      end
    end
  end


  def user_params
    params.require(:user)
    .permit(:email, :name, :gender, :avatar, :birthday, :address, :number_of_phone)
  end

  def load_user
    @user = User.find_by id: params[:id]
    return if @user
    flash[:error] = "Không tìm thấy người dùng"
    redirect_to members_users_path
  end
end

app/controllers/teachers/users_controller.rb
class Teachers::UsersController < DashboardController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :load_user, only: [:show, :edit, :update]
  before_action :valid_image_avatar, only: :update

  def show;end

  def edit; end

  def update
    if @user.update_attributes user_params
      create_activity_for_user
      flash[:success] = "Cập nhật thành công"
      redirect_to teachers_user_path
    else
      render :edit
    end
  end

  private

  def valid_image_avatar
    if params[:user][:avatar].present?
      unless Settings.image_types.to_h.values.include? File.extname(
        params[:user][:avatar].original_filename).split(".").last.downcase
        flash[:error] = "Ảnh quá lớn"
        redirect_to :back
      end
    end
  end

  def user_params
    params.require(:user)
    .permit(:email, :name, :gender, :avatar, :birthday, :address, :number_of_phone)
  end

  def load_user
    @user = User.find_by id: params[:id]
    return if @user
    flash[:error] = "Không tìm thấy người dùng"
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :authenticate_user!

  def after_update_path_for _resource
    if current_user.admin?
      return redirect_to admins_users_path
    elsif current_user.teacher?
      return redirect_to teachers_courses_path
    end
  end
end

app/helpers/teacher/users_helper.rb
module Teacher::UsersHelper
end

app/views/admins/users/_form.html.erb
<div class="clearfix form-horizontal">
  <br>
  <br>
  <div class="row">
    <%= form_for [:admins, @user] do |f| %>
      <div class="col-md-offset-1 col-md-3 row">
        <div class="text-center col-md-12">
          <%= image_tag @user.avatar.url, class: "height-250 width-250" %>
          <%= f.file_field :avatar, accept: Settings.image_format_accept %>
        </div>
      </div>
      <div class="col-md-offset-1 col-md-7 personal-info">
        <div class="clear-fix form-group row">
          <%= f.label :name, "Tên",
            class: "col-md-3 control-label field-compulsory-before" %>
          <div class="col-md-7">
            <div class="input-group">
              <div class="input-group-addon">
                <i class="gi gi-user"></i>
              </div>
              <%= f.text_field :name, class: "form-control",
                placeholder: "Tên" %>
            </div>
          </div>
        </div>

        <ul class="clear-fix  col-md-offset-3">
          <% @user.errors[:name].each do |msg| %>
            <li class="color-red"><%= msg %></li>
          <% end %>
        </ul>

        <div class="clearfix form-group row">
          <%= f.label :email,  "Email",
            class: "col-md-3 control-label field-compulsory-before" %>
          <div class="col-md-7">
            <div class="input-group">
              <div class="input-group-addon">
                <i class="gi gi-envelope"></i>
              </div>
              <%= f.text_field :email, class: "form-control",
                placeholder: "Email" %>
            </div>
          </div>
        </div>
        <ul class="clear-fix  col-md-offset-3">
          <% @user.errors[:email].each do |msg| %>
            <li class="color-red"><%= msg %></li>
          <% end %>
        </ul>

        <div class="clear-fix form-group">
          <%= f.label :number_of_phone, "Số điện thoại",
            class: "col-md-3 control-label field-compulsory-before" %>
          <div class="col-md-7">
            <div class="input-group">
              <div class="input-group-addon">
                <i class="hi hi-earphone"></i>
              </div>
              <%= f.text_field :number_of_phone, class: "form-control",
                placeholder: "Số điện thoại" %>
            </div>
          </div>
        </div>
        <ul class="clear-fix col-md-offset-3">
          <% @user.errors[:number_of_phone].each do |msg| %>
            <li class="color-red"><%= msg %></li>
          <% end %>
        </ul>

        <div class="clear-fix form-group">
          <%= f.label :address, "Địa chỉ", class: "col-md-3 control-label" %>
          <div class="col-md-7">
            <div class="input-group">
              <div class="input-group-addon">
                <i class="gi gi-home"></i>
              </div>
              <%= f.text_field :address, class: "form-control",
                placeholder: "Địa chỉ" %>
            </div>
          </div>
        </div>

        <div class="clear-fix form-group">
          <%= f.label :gender, "Giới tính", class: "col-md-3 control-label" %>
          <div class="col-md-7 select-container">
            <% User.genders.keys.each do |key| %>
              <%= f.radio_button :gender, key %>
              <%= t "admin.users.gender.#{key}" %>
              &nbsp;&nbsp;&nbsp;&nbsp;
            <% end %>
          </div>
        </div>

        <div class="clear-fix form-group">
          <%= f.label :role, "Quyền", class: "col-md-3 control-label" %>
          <div class="col-md-7 select-container">
            <% User.roles.keys.each do |key| %>
              <%= f.radio_button :role, key %>
              <%= t "admin.users.role.#{key}" %>
              &nbsp;&nbsp;&nbsp;&nbsp;
            <% end %>
          </div>
        </div>

        <div class="clear-fix form-group">
          <%= f.label :birthday, "Ngày sinh", class: "col-md-3 control-label" %>
          <div class="col-md-7">
            <div class="input-group">
              <div class="input-group-addon">
                <i class="gi gi-birthday_cake"></i>
              </div>
                <%= f.text_field :birthday,
                  value:(l @user.birthday, format: :date_month_year_v1 if @user.birthday.present?),
                  class: "form-control datepicker",
                  placeholder: "Ngày sinh" %>
            </div>
          </div>
        </div>
        <div class="clear-fix form-group row">
          <label class="col-md-3 control-label"></label>
          <div class="col-md-5">
            <%= f.submit yield(:button_text), class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/admins/users/_table_user.html.erb
<% if @users.present? %>
  <div class="table-responsive">
    <table class="table table-bordered table-hover">
      <thead>
        <tr class="table-center">
          <th class="font-size-15">Stt</th>
          <th class="font-size-15"><%= sort_link @search, :name, "Tên", {},
            {:remote => true} %>
          </th>
          <th class="font-size-15">Email</th>
          <th class="font-size-15">Số điện thoại</th>
          <th class="font-size-15">Quyền</th>
          <th class="text-center font-size-15">Thao tác</th>
        </tr>
      </thead>
      <tbody class="table-center">
        <%= render(@users, users: @users) %>
      </tbody>
    </table>
  </div>
  <center><%= paginate @users, remote: true %></center>
<% end %>

app/views/admins/users/_user.html.erb
<tr>
  <td>
    <%= current_index @users.current_page, Settings.per_page.admins.user,
      user_counter %>
  </td>
  <td><%= user.name %></td>
  <td><%= user.email %></td>
  <td><%= user.number_of_phone %></td>
  <td><%= t "user.role.#{user.role}" %></td>
  <td >
    <div class="btn-group btn-group-xs">
      <%= link_to admins_user_path(user), class: "btn btn-default" do %>
        <i class="fa fa-eye"></i>
      <% end %>
      <%= link_to edit_admins_user_path(user), class: "btn btn-warning" do %>
        <i class="fa fa-pencil"></i>
      <% end %>
      <%= link_to admins_user_path(user),
        method: :delete, class: "btn btn-danger", data: {confirm: "Bạn có chắc chắn muốn xóa không?"} do %>
        <i class="fa fa-trash"></i>
      <% end %>
    </div>
  </td>
</tr>

app/views/admins/users/index.html.erb
<% provide :title, "Danh sách người dùng" %>

<%= link_to new_admins_user_path,
  class: "btn btn-sm btn-success" do %>
  <i class="gi gi-plus"></i>Thêm thành viên
<% end %>
<br>
<br>

<div class="clear-fix panel panel-default">
  <div class="panel-heading">Tìm kiếm</div>
  <div class="panel-body">
    <%= search_form_for [:admins, @search], class: "row col-md-offset-1", remote: true do |f| %>
      <div class="form-group col-md-6">
        <%= f.text_field :name_or_email_cont,
          placeholder: "Nhập tên hoặc email để tìm kiếm",
          class: "form-control" %>
      </div>
      <div class="form-group col-md-2">
        <%= f.select :role_eq,
          @roles.collect {
            |value| [I18n.t("admin.roles.#{value[0]}"), value[1]]
          }, {include_blank: "Quyền"},
          class: "form-control" %>
      </div>
      &nbsp;&nbsp;
      <%= link_to admins_users_path do %>
        <i class="fa fa-refresh btn btn-success" id="refresh-page-list-user"></i>
      <% end %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="row clear-fix col-center color-red" id="not-exist-list-user">
  </div>
  <div class="col-md-12" id="list-user-search">
    <%= render "table_user" %>
  </div>
</div>

app/views/admins/users/index.js.erb
$('#list-user-search').html('<%= j render "table_user" %>');
$('#not-exist-list-user').html('<%= "Dữ liệu không tìm thấy" if @search.result.blank? %>');

app/views/admins/users/show.html.erb
<% provide :title, "Thông tin cá nhân" %>
<div class="panel-content">
  <div class="panel panel-info">
    <div class="panel-heading">
      <center>
        <h3 class="panel-title">
          Thông tin cá nhân
        </h3>
      </center>
    </div>
    <br>
    <br>
    <div class="panel-body">
      <div class="row">
        <div class="col-md-4" align="center">
          <%= image_tag @user.avatar.url, class: "height-250 width-250" %>
        </div>
        <div class="col-md-8 ">
          <table class="table table-hover">
            <tbody>
              <tr>
                <td>
                  <strong>
                    <i class="gi gi-user"></i> Tên
                  </strong>
                </td>
                <td><%= @user.name %></td>
              </tr>
              <tr>
                <td>
                  <strong>
                    <i class="gi gi-envelope"></i> Email
                  </strong>
                </td>
                <td><%= @user.email %></td>
              </tr>
              <tr>
                <td>
                  <strong>
                    <% if @user.male? %>
                      <i class="gi gi-male"></i>
                    <% elsif @user.female? %>
                      <i class="gi gi-female"></i>
                    <% end %>
                    Giới tính
                  </strong>
                </td>
                <td><%= I18n.t "user.gender.#{@user.gender}" %></td>
              </tr>
              <tr>
                <td>
                  <strong>
                    <i class="hi hi-earphone"></i> Số điện thoại
                  </strong>
                </td>
                <td><%= @user.number_of_phone %></td>
              </tr>
              <tr>
                <td>
                  <strong>
                    <i class="gi gi-home"></i> Địa chỉ
                  </strong>
                </td>
                <td><%= @user.address %></td>
              </tr>
              <tr>
                <td>
                  <strong>
                    <i class="gi gi-group"></i> Quyền
                  </strong>
                </td>
                <td><%= I18n.t "user.role.#{@user.role}" %></td>
              </tr>
              <tr>
                <td>
                  <strong>
                    <i class="gi gi-birthday_cake"></i> Ngày sinh
                  </strong>
                </td>
                <td><%= l @user.birthday, format: :date_month_year_v1 if @user.birthday.present? %></td>
              </tr>
            </tbody>
          </table>
          <% if @user.is_user? current_user %>
            <%= link_to "Thay đổi mật khẩu", edit_user_registration_path,
              class: "btn btn-primary" %>
            <%= link_to "Chỉnh sửa thông tin",
              edit_admins_user_path(current_user), class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>